version: '3.8'
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RoadFreightTransportation
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "RoadFreightTransportation"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build: .
    container_name: app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: RoadFreightTransportation
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
    command: ["npm", "start"]

networks:
  mynetwork:
    driver: bridge
